apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: #OPERATOR_NAME#-v#OPERATOR_VERSION#
  namespace: pagerduty-operator
  annotations:
    categories: A list of comma separated categories that your operator falls under.
    certified: "false"
    description: OpenShift cluster provisioning and management at scale.
    containerImage: #OPERATOR_IMAGE#
    createdAt: "$TIME"
    support: OSD SRE
spec:
  displayName: pagerduty-operator
  description: SRE operator - pagerduty-operator
  keywords:
  - kubernetes
  - openshift
  - multi-cluster
  - cluster
  version: #OPERATOR_VERSION#
  provider:
    name: Red Hat, Inc
  maturity: alpha
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: true
  - type: AllNamespaces
    supported: false
  install:
    strategy: deployment
    spec:
      clusterPermissions: []
        # Rules will be added here by the generate-operator-bundle.py script.
      deployments:
      - name: pagerduty-operator
  customresourcedefinitions:
    owned:
    - description: PagerDutyIntegration
      displayName: PagerDutyIntegration
      kind: PagerDutyIntegration
      name: pagerdutyintegrations.pagerduty.10gen.io
      version: v1alpha1
